export { generateTournamentSchedule, generateUnscheduled, validateConfig, withDistributedGroups } from "./generate";
export { scheduleMatches } from "./schedule";
export { computeStandings, standingsByGroup } from "./standings";
export { computeScorers } from "./scorers";
export { generateKnockoutMatches, generateNextKnockout, knockoutRoundLabel, nextKnockoutRound, pairQualified, qualifiedFromStandings } from "./knockout";
export { generateRoundRobin } from "./roundRobin";
export { distributeTeams, groupNameAt, teamsByGroup } from "./groups";
export { buildSlots, parseLocalDate } from "./dates";
export { computeDefense } from "./defense";
export type { DefenseRow, GeneratedMatch, ScheduleResult, StandingRow, TeamInput, TournamentConfig } from "./types";
